### ISSUE TITLE
Add clang-format-10 to Dockerfile

### ISSUE THREAD

**Issue by insooth** [UmlautSoftwareDevelopmentAccount/AUTOSAR-Adaptive#13]
Idea: run script from https://apt.llvm.org/ and `apt-get update && apt-get install clang-format-10`.

https://github.com/UmlautSoftwareDevelopmentAccount/AUTOSAR-Adaptive/blob/e39273d540f7373c19bc420b8cb653c9770c273d/tools/docker/development-env/Dockerfile#L19

**Comment by bburda** [comment]
There is already `clang-format-11`, so I think that we can use it instead.
