### ISSUE TITLE
Fix the URL to the Pitchfork Layout in ADR

### ISSUE THREAD

**Issue by bburda** [UmlautSoftwareDevelopmentAccount/AUTOSAR-Adaptive#18]
The [ADR file](https://github.com/UmlautSoftwareDevelopmentAccount/AUTOSAR-Adaptive/blob/master/docs/architectural/decisions/project-structure-pitchfork-layout.md#decision)

Mentioned URL is in the sentence:
We will use _the Pitchfork layout_ for the whole project.

**Comment by satletio1** [comment]
Link starts work...

can be closed
