### ISSUE TITLE
Extend AUTOSAR-Adaptive wiki with Technology stack

### ISSUE THREAD

**Issue by satletio1** [UmlautSoftwareDevelopmentAccount/AUTOSAR-Adaptive#25]
Extend AUTOSAR-Adaptive wiki with:
- technology stack
- links to documentation and tutorials (maybe YT)
- create a linked list like:

1. Intro
2. How to install
3. Tech stack

**Comment by satletio1** [comment]
Simple list added.
Technology stack to be filled.

**Comment by bburda** [comment]
It would be good, If we attach each technology into the V-Model diagram.
![vmodel](https://user-images.githubusercontent.com/24573178/84418273-39abb100-ac17-11ea-866b-db9b62a25c8a.png)

Like: 
Planning - GitHub
Maintenence - GitHub
Architecture - PlantUML
Detailed Design - PlantUML
Implementation - C++20, Python3 
etc.

**Comment by satletio1** [comment]
Cool Idea.
Just for reminding, we can use:
https://www.smartdraw.com/v-model/examples/
or just Draw.IO

Will do it in 'spare time'

**Comment by satletio1** [comment]
Link to editable template:
https://cloud.smartdraw.com/editor.aspx?templateId=1bf7dc72-a8cf-4743-b652-339cc1e58293&noro=1&nsu=1#depoId=20237054&credID=-30911954

**Comment by bburda** [comment]
Creating the V-Model with project tooling will be moved to another issue. Closing this one.
