### ISSUE TITLE
Create a tool for parsing AUTOSAR PDFs SWS/RS files to the parsable format like CSV

### ISSUE THREAD

**Issue by bburda** [UmlautSoftwareDevelopmentAccount/AUTOSAR-Adaptive#8]
We need the AUTOSAR requirements in a parsable format, to be able to provide requirement/code requirement/architecture traceability.

**Comment by insooth** [comment]
I wonder whether it would be possible to realise as (with additional steps to inject opening and closing braces to `$SPEC.json`):

```
pdftotext -f $FIRST_PAGE -l $LAST_PAGE $SPEC.pdf | sed $EXPR >> $SPEC.json
```

and to extend the above described tool to produces more detailed JSON description that may be used to be transformed by `jq` tool, and to automatically generate header files as defined in `$SPEC.pdf`.

Example output:

```
{
  "id":"SWS_PER_00322"
, "type":"DRAFT"
, "kind":"function"
, "symbol":"ara::per::KeyValueStorage::KeyValueStorage(KeyValueStorage &&kvs)"
, "scope":"class ara::per::KeyValueStorage"
, "syntax":"KeyValueStorage (KeyValueStorage &&kvs) noexcept;"
...
}
```

from:

```
[SWS_PER_00322]{DRAFT} d
Kind:

function

Symbol:

ara::per::KeyValueStorage::KeyValueStorage(KeyValueStorage &&kvs)

Scope:

class ara::per::KeyValueStorage

Syntax:

KeyValueStorage (KeyValueStorage &&kvs) noexcept;

...
```

JSON structure should be enabled with #10.
