### ISSUE TITLE
Set up CI/CD basic pipeline

### ISSUE THREAD

**Issue by bburda** [UmlautSoftwareDevelopmentAccount/AUTOSAR-Adaptive#9]
Set up CI/CD for the whole platform using Travis

**Comment by satletio1** [comment]
Some remarks/questions:

1. How CI should be structured?
- build whole project or
- build separate subproject 

2. Should we schedule daily build (i.e. 4pm) or builds will be created only by push trigger?

**Comment by bburda** [comment]
The other repos has Travis setup. I will create tasks as needed. Now it can be closed.
